(define (fast-expt b n)
 (define (fast-expt-iter step a)
  (cond ((= step 0) a)
        ((even step) (fast-expt-iter (/ step 2) (* a b b)))
        (else (fast-expt-iter (- step 1) (* a b)))))
 (fast-expt-iter (- n 1) 1))
